"""
AI Image Generation Service using Gemini 3 Pro Image (Nano Banana Pro)
"""

from google import genai
from google.genai import types
from app.core.config import settings
from app.core.logging import logger
from typing import Optional, Dict, Any
import base64
from io import BytesIO
from PIL import Image


class GenerationService:
    """Service for generating icons using Gemini 3 Pro Image"""

    def __init__(self):
        """Initialize Gemini API"""
        if settings.GEMINI_API_KEY:
            self.client = genai.Client(api_key=settings.GEMINI_API_KEY)
            logger.info("Gemini 3 Pro Image client configured")
        else:
            self.client = None
            logger.warning("Gemini API key not configured")

    def _build_prompt(
        self,
        concept: str,
        style: str = "finary-glass-3d",
        category: Optional[str] = None
    ) -> str:
        """
        Build detailed prompt for icon generation using Finary's exact style
        NO GROUND REFLECTION as specified
        """
        # Using the final optimized Finary prompt template
        prompt = f"""3D {concept}, minimalist geometric sculptural form, translucent crystal glass material, semi-transparent blue glass #8DADFF with inner light showing through, smooth satin surface finish, warm amber-peach internal glow #F1C086 visible through the glass from behind, deep navy blue #2D4A6B in shadowed areas, bright white-blue highlights on top edges, glass subsurface scattering effect, simplified iconic shape, dynamic three-quarter angle view from slightly above, soft warm backlight creating internal glow, cool front key lighting, solid pure black background #000000, single floating isolated object centered in frame, no outline, no external glow, no bloom, no ground plane, no reflection, no shadow on background, clean UI icon aesthetic, professional CGI render, octane render, 8k resolution"""

        return prompt

    def _build_animation_prompt(
        self,
        concept: str,
        style: str = "finary-glass-3d"
    ) -> str:
        """Build prompt for video animation"""
        return f"""Animation prompt for motion design:

Icon: {concept} (Finary glass 3D style)

Animation sequence (3-5 seconds):
1. Entry (0-1s): Gentle float in from above with subtle rotation
2. Idle (1-3s): Soft floating motion with slight scale breathing (0.98-1.02)
3. Highlight (3-4s): Gentle glow pulse and rotate 15 degrees
4. Exit (4-5s): Fade out with slight upward float

Effects:
- Smooth easing (ease-in-out)
- Subtle glass reflection animations
- Soft glow on interaction/highlight
- Maintain depth and 3D feeling throughout
- No ground shadows or reflections

Style: Professional, elegant, understated"""

    async def generate_icon(
        self,
        concept: str,
        style: str = "finary-glass-3d",
        category: Optional[str] = None,
        size: str = "2048x2048"
    ) -> Dict[str, Any]:
        """
        Generate icon using Gemini 3 Pro Image (Nano Banana Pro)

        Returns:
            Dict with image_data (base64), prompt, and animation_prompt
        """
        if not self.client:
            raise Exception("Gemini client not initialized")

        try:
            prompt = self._build_prompt(concept, style, category)
            animation_prompt = self._build_animation_prompt(concept, style)

            logger.info(f"Generating icon for concept: {concept}")

            # Generate image using Gemini 3 Pro Image
            response = self.client.models.generate_content(
                model="gemini-3-pro-image-preview",  # Gemini 3 Pro Image
                contents=[prompt],
            )

            # Extract generated image from response
            image_bytes = None
            for part in response.parts:
                if part.inline_data is not None:
                    # Get raw image bytes directly from inline_data
                    image_bytes = part.inline_data.data
                    break

            if image_bytes is None:
                raise Exception("No image generated by Gemini")

            # Convert bytes to base64
            image_base64 = base64.b64encode(image_bytes).decode('utf-8')

            logger.info(f"Successfully generated icon for: {concept}")

            return {
                "image_data": image_base64,
                "prompt": prompt,
                "animation_prompt": animation_prompt,
                "concept": concept,
                "style": style,
                "size": size
            }

        except Exception as e:
            logger.error(f"Failed to generate icon for {concept}: {str(e)}")
            raise

    async def generate_icon_from_concept(
        self,
        concept: str,
        category: Optional[str] = None,
        visual_description: Optional[str] = None
    ) -> Optional[bytes]:
        """
        Generate icon from concept and return raw image bytes

        Args:
            concept: The concept name to generate
            category: Optional category
            visual_description: Optional detailed visual description (not used with template)

        Returns:
            Image bytes or None if generation fails
        """
        try:
            result = await self.generate_icon(
                concept=concept,
                category=category
            )

            if result and "image_data" in result:
                # Convert base64 back to bytes
                return base64.b64decode(result["image_data"])

            return None

        except Exception as e:
            logger.error(f"Failed to generate icon from concept {concept}: {str(e)}")
            return None

    async def generate_icon_batch(
        self,
        concepts: list[str],
        style: str = "finary-glass-3d",
        category: Optional[str] = None
    ) -> list[Dict[str, Any]]:
        """Generate multiple icons in batch"""
        results = []

        for concept in concepts:
            try:
                result = await self.generate_icon(concept, style, category)
                results.append(result)
            except Exception as e:
                logger.error(f"Failed to generate icon for {concept}: {str(e)}")
                results.append({
                    "concept": concept,
                    "error": str(e)
                })

        return results


# Singleton instance
generation_service = GenerationService()
